format = "cosmo-preset"
id = "factory-002-2line-w-reverb"
name = "2LINE W/REVERB"
author = "Temple of CZ"
description = ""
tags = ["synth", "lead"]
starred = false
favorite = false
source = "cz-factory"

[params]
czDacEnabled = false
frequency = 440
legato = false
lineSelect = "L1+L2'"
macro1 = 0
macro2 = 0
macro3 = 0
macro4 = 0
macroLabels = ["Brightness", "Timbre", "Time", "Movement"]
modMode = "normal"
octave = 0
pitchBendRange = 2
polyMode = "poly8"
ringGain = 4
tempoBpm = 120
velocityCurve = 0
volume = 1

[params.line1]
algo = "cz101"
algo2 = "cz101"
algoBlend = 0
algoControlsA = [{ id = "preset", value = 0 }, { id = "waveform1", value = 4 }, { id = "waveform2", value = 2 }, { id = "windowFunction", value = 0 }]
algoControlsB = [{ id = "preset", value = 2 }, { id = "waveform1", value = 2 }, { id = "waveform2", value = 2 }, { id = "windowFunction", value = 0 }]
baseWaveformA = "cosine"
baseWaveformB = "cosine"
dcaBase = 1
dcaKeyFollow = 9
dcwBase = 1
dcwKeyFollow = 9
detuneFine = 0
detuneNote = 0
modulation = 0
octave = 0
window = "off"

[params.line1.dcoEnv]
loop = false
stepCount = 1
steps = [[0, 0], [0, 50], [0, 50], [0, 50], [0, 50], [0, 50], [0, 50], [0, 50]]
sustainStep = 0

[params.line1.dcwEnv]
loop = false
stepCount = 1
steps = [[0, 0], [0, 50], [0, 50], [0, 50], [0, 50], [0, 50], [0, 50], [0, 50]]
sustainStep = 0

[params.line1.dcaEnv]
loop = false
stepCount = 8
steps = [[99, 75], [84, 75], [28, 49], [75, 49], [0, 49], [70, 49], [0, 39], [0, 50]]
sustainStep = 1

[params.line2]
algo = "cz101"
algoBlend = 0
algoControlsA = [{ id = "preset", value = 3 }, { id = "waveform1", value = 4 }, { id = "waveform2", value = 4 }, { id = "windowFunction", value = 0 }]
algoControlsB = []
baseWaveformA = "cosine"
baseWaveformB = "cosine"
dcaBase = 1
dcaKeyFollow = 1
dcwBase = 1
dcwKeyFollow = 1
detuneFine = 0
detuneNote = 0
modulation = 0
octave = 0
window = "off"

[params.line2.dcoEnv]
loop = false
stepCount = 1
steps = [[0, 0], [0, 50], [0, 50], [0, 50], [0, 50], [0, 50], [0, 50], [0, 50]]
sustainStep = 0

[params.line2.dcwEnv]
loop = false
stepCount = 2
steps = [[12, 99], [0, 12], [0, 50], [0, 50], [0, 50], [0, 50], [0, 50], [0, 50]]
sustainStep = 1

[params.line2.dcaEnv]
loop = false
stepCount = 2
steps = [[99, 95], [0, 30], [0, 50], [0, 50], [0, 50], [0, 50], [0, 50], [0, 50]]
sustainStep = 1

[params.portamento]
enabled = false
mode = "time"
rate = 0
time = 0.1

[params.lfo]
depth = 1
offset = 0
rate = 5
rateMode = "hz"
retrigger = false
symmetry = 0.5
syncDivision = "quarter"
waveform = "sine"

[params.lfo2]
depth = 0
offset = 0
rate = 5
rateMode = "hz"
retrigger = false
symmetry = 0.5
syncDivision = "quarter"
waveform = "sine"

[params.random]
rate = 2

[params.modEnv]
attack = 0.01
decay = 0.1
release = 0.2
sustain = 0.5

[params.fx.slot4]
type = "vibrato"

[params.fx.slot4.params]
delay = 33
depth = 0
enabled = false
rate = 55
rate_mode = "hz"
sync_division = "quarter"
waveform = 1
