format = "cosmo-preset"
formatVersion = 1
presetSchemaVersion = 1
id = "factory-012-alien-1"
name = "ALIEN 1"
author = "Temple of CZ"
description = ""
tags = ["effect"]
starred = false
favorite = false
source = "cz-factory"

[params]
lineSelect = "L1+L2'"
modMode = "ring"
octave = 0
frequency = 440
volume = 1
polyMode = "poly8"
legato = false
velocityCurve = 0
pitchBendRange = 2
fxSlots = [{ type = "empty" }, { type = "empty" }, { type = "empty" }, { type = "vibrato", params = { enabled = true, waveform = 4, rate = 60, depth = 50, delay = 0 } }, { type = "empty" }, { type = "empty" }]

[params.line1]
algo = "cz101"
algoBlend = 0
baseWaveformA = "cosine"
baseWaveformB = "cosine"
window = "off"
dcaBase = 1
dcwBase = 1
modulation = 0
detuneNote = 0
detuneFine = 0
octave = 1
dcwKeyFollow = 0
dcaKeyFollow = 0
algoControlsA = [{ id = "preset", value = 1 }, { id = "waveform1", value = 1 }, { id = "waveform2", value = 1 }, { id = "windowFunction", value = 0 }]
algoControlsB = []

[params.line1.dcoEnv]
steps = [[0, 99], [0, 50], [0, 50], [0, 50], [0, 50], [0, 50], [0, 50], [0, 50]]
sustainStep = 0
stepCount = 1
loop = false

[params.line1.dcwEnv]
steps = [[84, 76], [0, 37], [0, 50], [0, 50], [0, 50], [0, 50], [0, 50], [0, 50]]
sustainStep = 1
stepCount = 2
loop = false

[params.line1.dcaEnv]
steps = [[99, 27], [80, 46], [0, 22], [0, 50], [0, 50], [0, 50], [0, 50], [0, 50]]
sustainStep = 1
stepCount = 3
loop = false

[params.line2]
algo = "cz101"
algoBlend = 0
baseWaveformA = "cosine"
baseWaveformB = "cosine"
window = "off"
dcaBase = 1
dcwBase = 1
modulation = 0
detuneNote = 1
detuneFine = 39
octave = 1
dcwKeyFollow = 0
dcaKeyFollow = 0
algoControlsA = [{ id = "preset", value = 1 }, { id = "waveform1", value = 1 }, { id = "waveform2", value = 1 }, { id = "windowFunction", value = 0 }]
algoControlsB = []

[params.line2.dcoEnv]
steps = [[0, 99], [0, 50], [0, 50], [0, 50], [0, 50], [0, 50], [0, 50], [0, 50]]
sustainStep = 0
stepCount = 1
loop = false

[params.line2.dcwEnv]
steps = [[42, 76], [0, 89], [0, 50], [0, 50], [0, 50], [0, 50], [0, 50], [0, 50]]
sustainStep = 1
stepCount = 2
loop = false

[params.line2.dcaEnv]
steps = [[99, 33], [81, 23], [0, 22], [0, 50], [0, 50], [0, 50], [0, 50], [0, 50]]
sustainStep = 1
stepCount = 3
loop = false

[params.portamento]
enabled = false
mode = "time"
rate = 0
time = 0.1

[params.lfo]
waveform = "sine"
rate = 5
depth = 1
symmetry = 0.5
retrigger = false
offset = 0

[params.lfo2]
waveform = "sine"
rate = 5
depth = 0
symmetry = 0.5
retrigger = false
offset = 0

[params.random]
rate = 2

[params.modEnv]
attack = 0.009999999776482582
decay = 0.10000000149011612
sustain = 0.5
release = 0.20000000298023224

[params.modMatrix]
routes = []
