format = "cosmo-preset"
formatVersion = 1
presetSchemaVersion = 1
id = "factory-036-cello-1"
name = "CELLO 1"
author = "Temple of CZ"
description = ""
tags = ["string"]
starred = false
favorite = false
source = "cz-factory"

[params]
lineSelect = "L1+L1'"
modMode = "ring"
octave = 0
frequency = 440
volume = 1
polyMode = "poly8"
legato = false
velocityCurve = 0
pitchBendRange = 2
fxSlots = [{ type = "empty" }, { type = "empty" }, { type = "empty" }, { type = "vibrato", params = { enabled = true, waveform = 1, rate = 50, depth = 8, delay = 32 } }, { type = "empty" }, { type = "empty" }]

[params.line1]
algo = "cz101"
algo2 = "cz101"
algoBlend = 0
baseWaveformA = "cosine"
baseWaveformB = "cosine"
window = "off"
dcaBase = 1
dcwBase = 1
modulation = 0
detuneNote = 0
detuneFine = 0
octave = 0
dcwKeyFollow = 0
dcaKeyFollow = 0
algoControlsA = [{ id = "preset", value = 0 }, { id = "waveform1", value = 0 }, { id = "waveform2", value = 4 }, { id = "windowFunction", value = 0 }]
algoControlsB = [{ id = "preset", value = 3 }, { id = "waveform1", value = 4 }, { id = "waveform2", value = 4 }, { id = "windowFunction", value = 0 }]

[params.line1.dcoEnv]
steps = [[66, 99], [66, 43], [0, 0], [0, 50], [0, 50], [0, 50], [0, 50], [0, 50]]
sustainStep = 2
stepCount = 3
loop = false

[params.line1.dcwEnv]
steps = [[86, 83], [50, 59], [48, 31], [0, 85], [0, 50], [0, 50], [0, 50], [0, 50]]
sustainStep = 1
stepCount = 4
loop = false

[params.line1.dcaEnv]
steps = [[81, 62], [94, 34], [85, 25], [0, 50], [0, 50], [0, 50], [0, 50], [0, 50]]
sustainStep = 2
stepCount = 8
loop = false

[params.line2]
algo = "cz101"
algoBlend = 0
baseWaveformA = "cosine"
baseWaveformB = "cosine"
window = "off"
dcaBase = 1
dcwBase = 1
modulation = 0
detuneNote = 0
detuneFine = 0
octave = 0
dcwKeyFollow = 1
dcaKeyFollow = 1
algoControlsA = [{ id = "preset", value = 1 }, { id = "waveform1", value = 1 }, { id = "waveform2", value = 1 }, { id = "windowFunction", value = 0 }]
algoControlsB = []

[params.line2.dcoEnv]
steps = [[0, 50], [0, 50], [0, 50], [0, 50], [0, 50], [0, 50], [0, 50], [0, 50]]
sustainStep = 0
stepCount = 1
loop = false

[params.line2.dcwEnv]
steps = [[65, 98], [0, 38], [0, 50], [0, 50], [0, 50], [0, 50], [0, 50], [0, 50]]
sustainStep = 1
stepCount = 2
loop = false

[params.line2.dcaEnv]
steps = [[99, 95], [0, 23], [0, 50], [0, 50], [0, 50], [0, 50], [0, 50], [0, 50]]
sustainStep = 1
stepCount = 2
loop = false

[params.portamento]
enabled = false
mode = "time"
rate = 0
time = 0.1

[params.lfo]
waveform = "sine"
rate = 5
depth = 1
symmetry = 0.5
retrigger = false
offset = 0

[params.lfo2]
waveform = "sine"
rate = 5
depth = 0
symmetry = 0.5
retrigger = false
offset = 0

[params.random]
rate = 2

[params.modEnv]
attack = 0.009999999776482582
decay = 0.10000000149011612
sustain = 0.5
release = 0.20000000298023224

[params.modMatrix]
routes = []
