format = "cosmo-preset"
id = "factory-051-echo-fantasy"
name = "ECHO FANTASY"
author = "Temple of CZ"
description = ""
tags = ["brass"]
starred = false
favorite = false
source = "cz-factory"

[params]
czDacEnabled = false
frequency = 440
legato = false
lineSelect = "L1+L1'"
macro1 = 0
macro2 = 0
macro3 = 0
macro4 = 0
macroLabels = ["Brightness", "Timbre", "Time", "Movement"]
modMode = "normal"
octave = 0
pitchBendRange = 2
polyMode = "poly8"
ringGain = 4
tempoBpm = 120
velocityCurve = 0
volume = 1

[params.line1]
algo = "cz101"
algo2 = "cz101"
algoBlend = 0
algoControlsA = [{ id = "preset", value = 3 }, { id = "waveform1", value = 4 }, { id = "waveform2", value = 4 }, { id = "windowFunction", value = 0 }]
algoControlsB = [{ id = "preset", value = 3 }, { id = "waveform1", value = 4 }, { id = "waveform2", value = 4 }, { id = "windowFunction", value = 0 }]
baseWaveformA = "cosine"
baseWaveformB = "cosine"
dcaBase = 1
dcaKeyFollow = 6
dcwBase = 1
dcwKeyFollow = 6
detuneFine = 0
detuneNote = 0
modulation = 0
octave = 0
window = "off"

[params.line1.dcoEnv]
loop = false
stepCount = 1
steps = [[87, 99], [0, 50], [0, 50], [0, 50], [0, 50], [0, 50], [0, 50], [0, 50]]
sustainStep = 0

[params.line1.dcwEnv]
loop = false
stepCount = 7
steps = [[66, 83], [26, 48], [68, 50], [41, 50], [59, 50], [31, 50], [0, 29], [0, 50]]
sustainStep = 1

[params.line1.dcaEnv]
loop = false
stepCount = 8
steps = [[99, 75], [84, 75], [30, 50], [89, 50], [15, 50], [77, 51], [9, 50], [0, 32]]
sustainStep = 1

[params.line2]
algo = "cz101"
algoBlend = 0
algoControlsA = [{ id = "preset", value = 0 }, { id = "waveform1", value = 0 }, { id = "waveform2", value = 0 }, { id = "windowFunction", value = 0 }]
algoControlsB = []
baseWaveformA = "cosine"
baseWaveformB = "cosine"
dcaBase = 1
dcaKeyFollow = 9
dcwBase = 1
dcwKeyFollow = 9
detuneFine = 3
detuneNote = 0
modulation = 0
octave = 0
window = "off"

[params.line2.dcoEnv]
loop = false
stepCount = 1
steps = [[0, 99], [0, 50], [0, 50], [0, 50], [0, 50], [0, 50], [0, 50], [0, 50]]
sustainStep = 0

[params.line2.dcwEnv]
loop = false
stepCount = 2
steps = [[40, 99], [0, 99], [0, 50], [0, 50], [0, 50], [0, 50], [0, 50], [0, 50]]
sustainStep = 0

[params.line2.dcaEnv]
loop = false
stepCount = 4
steps = [[57, 99], [0, 56], [0, 38], [0, 46], [0, 50], [0, 50], [0, 50], [0, 50]]
sustainStep = 2

[params.portamento]
enabled = false
mode = "time"
rate = 0
time = 0.1

[params.lfo]
depth = 1
offset = 0
rate = 5
rateMode = "hz"
retrigger = false
symmetry = 0.5
syncDivision = "quarter"
waveform = "sine"

[params.lfo2]
depth = 0
offset = 0
rate = 5
rateMode = "hz"
retrigger = false
symmetry = 0.5
syncDivision = "quarter"
waveform = "sine"

[params.random]
rate = 2

[params.modEnv]
attack = 0.01
decay = 0.1
release = 0.2
sustain = 0.5

[params.fx.slot4]
type = "vibrato"

[params.fx.slot4.params]
delay = 53
depth = 3
enabled = true
rate = 51
rate_mode = "hz"
sync_division = "quarter"
waveform = 1
