format = "cosmo-preset"
id = "factory-052-elec-bass-a"
name = "ELEC. BASS A"
author = "Temple of CZ"
description = ""
tags = ["bass"]
starred = false
favorite = false
source = "cz-factory"

[params]
czDacEnabled = false
frequency = 440
legato = false
lineSelect = "L1+L1'"
macro1 = 0
macro2 = 0
macro3 = 0
macro4 = 0
macroLabels = ["Brightness", "Timbre", "Time", "Movement"]
modMode = "normal"
octave = 0
pitchBendRange = 2
polyMode = "poly8"
ringGain = 4
tempoBpm = 120
velocityCurve = 0
volume = 1

[params.line1]
algo = "cz101"
algo2 = "cz101"
algoBlend = 0
algoControlsA = [{ id = "preset", value = 0 }, { id = "waveform1", value = 2 }, { id = "waveform2", value = 0 }, { id = "windowFunction", value = 0 }]
algoControlsB = [{ id = "preset", value = 0 }, { id = "waveform1", value = 0 }, { id = "waveform2", value = 0 }, { id = "windowFunction", value = 0 }]
baseWaveformA = "cosine"
baseWaveformB = "cosine"
dcaBase = 1
dcaKeyFollow = 9
dcwBase = 1
dcwKeyFollow = 9
detuneFine = 0
detuneNote = 0
modulation = 0
octave = -1
window = "off"

[params.line1.dcoEnv]
loop = false
stepCount = 2
steps = [[66, 99], [0, 99], [0, 50], [0, 50], [0, 50], [0, 50], [0, 50], [0, 50]]
sustainStep = 1

[params.line1.dcwEnv]
loop = false
stepCount = 4
steps = [[80, 99], [45, 45], [30, 40], [0, 41], [0, 50], [0, 50], [0, 50], [0, 50]]
sustainStep = 2

[params.line1.dcaEnv]
loop = false
stepCount = 4
steps = [[92, 93], [73, 25], [49, 35], [0, 82], [0, 50], [0, 50], [0, 50], [0, 50]]
sustainStep = 2

[params.line2]
algo = "cz101"
algo2 = "cz101"
algoBlend = 0
algoControlsA = [{ id = "preset", value = 0 }, { id = "waveform1", value = 0 }, { id = "waveform2", value = 6 }, { id = "windowFunction", value = 2 }]
algoControlsB = [{ id = "preset", value = 6 }, { id = "waveform1", value = 6 }, { id = "waveform2", value = 6 }, { id = "windowFunction", value = 2 }]
baseWaveformA = "cosine"
baseWaveformB = "cosine"
dcaBase = 1
dcaKeyFollow = 0
dcwBase = 1
dcwKeyFollow = 0
detuneFine = 0
detuneNote = 0
modulation = 0
octave = -1
window = "off"

[params.line2.dcoEnv]
loop = false
stepCount = 1
steps = [[0, 0], [0, 50], [0, 50], [0, 50], [0, 50], [0, 50], [0, 50], [0, 50]]
sustainStep = 0

[params.line2.dcwEnv]
loop = false
stepCount = 4
steps = [[40, 99], [96, 78], [99, 11], [0, 41], [0, 50], [0, 50], [0, 50], [0, 50]]
sustainStep = 2

[params.line2.dcaEnv]
loop = false
stepCount = 2
steps = [[90, 93], [0, 39], [0, 50], [0, 50], [0, 50], [0, 50], [0, 50], [0, 50]]
sustainStep = 0

[params.portamento]
enabled = false
mode = "time"
rate = 0
time = 0.1

[params.lfo]
depth = 1
offset = 0
rate = 5
rateMode = "hz"
retrigger = false
symmetry = 0.5
syncDivision = "quarter"
waveform = "sine"

[params.lfo2]
depth = 0
offset = 0
rate = 5
rateMode = "hz"
retrigger = false
symmetry = 0.5
syncDivision = "quarter"
waveform = "sine"

[params.random]
rate = 2

[params.modEnv]
attack = 0.01
decay = 0.1
release = 0.2
sustain = 0.5

[params.fx.slot4]
type = "vibrato"

[params.fx.slot4.params]
delay = 0
depth = 1
enabled = true
rate = 20
rate_mode = "hz"
sync_division = "quarter"
waveform = 3
