format = "cosmo-preset"
formatVersion = 1
presetSchemaVersion = 1
id = "factory-063-envfltrfatorgn"
name = "ENVFLTRFATORGN"
author = "Temple of CZ"
description = ""
tags = ["organ"]
starred = false
favorite = false
source = "cz-factory"

[params]
lineSelect = "L1+L2'"
modMode = "normal"
octave = 0
frequency = 440
volume = 1
polyMode = "poly8"
legato = false
velocityCurve = 0
pitchBendRange = 2
fxSlots = [{ type = "empty" }, { type = "empty" }, { type = "empty" }, { type = "vibrato", params = { enabled = true, waveform = 1, rate = 52, depth = 5, delay = 51 } }, { type = "empty" }, { type = "empty" }]

[params.line1]
algo = "cz101"
algoBlend = 0
baseWaveformA = "cosine"
baseWaveformB = "cosine"
window = "off"
dcaBase = 1
dcwBase = 1
modulation = 0
detuneNote = 0
detuneFine = 0
octave = -1
dcwKeyFollow = 9
dcaKeyFollow = 9
algoControlsA = [{ id = "preset", value = 7 }, { id = "waveform1", value = 6 }, { id = "waveform2", value = 6 }, { id = "windowFunction", value = 3 }]
algoControlsB = []

[params.line1.dcoEnv]
steps = [[0, 99], [0, 50], [0, 50], [0, 50], [0, 50], [0, 50], [0, 50], [0, 50]]
sustainStep = 0
stepCount = 1
loop = false

[params.line1.dcwEnv]
steps = [[99, 82], [0, 50], [0, 50], [0, 50], [0, 50], [0, 50], [0, 50], [0, 50]]
sustainStep = 0
stepCount = 8
loop = false

[params.line1.dcaEnv]
steps = [[99, 94], [99, 55], [0, 21], [0, 60], [0, 50], [0, 50], [0, 50], [0, 50]]
sustainStep = 2
stepCount = 4
loop = false

[params.line2]
algo = "cz101"
algoBlend = 0
baseWaveformA = "cosine"
baseWaveformB = "cosine"
window = "off"
dcaBase = 1
dcwBase = 1
modulation = 0
detuneNote = 0
detuneFine = 0
octave = -2
dcwKeyFollow = 9
dcaKeyFollow = 9
algoControlsA = [{ id = "preset", value = 3 }, { id = "waveform1", value = 4 }, { id = "waveform2", value = 4 }, { id = "windowFunction", value = 0 }]
algoControlsB = []

[params.line2.dcoEnv]
steps = [[0, 99], [0, 50], [0, 50], [0, 50], [0, 50], [0, 50], [0, 50], [0, 50]]
sustainStep = 0
stepCount = 1
loop = false

[params.line2.dcwEnv]
steps = [[40, 99], [0, 99], [0, 50], [0, 50], [0, 50], [0, 50], [0, 50], [0, 50]]
sustainStep = 0
stepCount = 2
loop = false

[params.line2.dcaEnv]
steps = [[57, 99], [0, 56], [98, 55], [0, 46], [0, 50], [0, 50], [0, 50], [0, 50]]
sustainStep = 2
stepCount = 4
loop = false

[params.portamento]
enabled = false
mode = "time"
rate = 0
time = 0.1

[params.lfo]
waveform = "sine"
rate = 5
depth = 1
symmetry = 0.5
retrigger = false
offset = 0

[params.lfo2]
waveform = "sine"
rate = 5
depth = 0
symmetry = 0.5
retrigger = false
offset = 0

[params.random]
rate = 2

[params.modEnv]
attack = 0.009999999776482582
decay = 0.10000000149011612
sustain = 0.5
release = 0.20000000298023224

[params.modMatrix]
routes = []
