format = "cosmo-preset"
id = "factory-064-fade-brass"
name = "FADE BRASS"
author = "Temple of CZ"
description = ""
tags = ["brass"]
starred = false
favorite = false
source = "cz-factory"

[params]
czDacEnabled = false
frequency = 440
legato = false
lineSelect = "L1+L1'"
macro1 = 0
macro2 = 0
macro3 = 0
macro4 = 0
macroLabels = ["Brightness", "Timbre", "Time", "Movement"]
modMode = "normal"
octave = 0
pitchBendRange = 2
polyMode = "poly8"
ringGain = 4
tempoBpm = 120
velocityCurve = 0
volume = 1

[params.line1]
algo = "cz101"
algoBlend = 0
algoControlsA = [{ id = "preset", value = 4 }, { id = "waveform1", value = 5 }, { id = "waveform2", value = 5 }, { id = "windowFunction", value = 0 }]
algoControlsB = []
baseWaveformA = "cosine"
baseWaveformB = "cosine"
dcaBase = 1
dcaKeyFollow = 8
dcwBase = 1
dcwKeyFollow = 8
detuneFine = 0
detuneNote = 0
modulation = 0
octave = 0
window = "off"

[params.line1.dcoEnv]
loop = false
stepCount = 1
steps = [[9, 88], [0, 50], [0, 50], [0, 50], [0, 50], [0, 50], [0, 50], [0, 50]]
sustainStep = 0

[params.line1.dcwEnv]
loop = false
stepCount = 2
steps = [[99, 60], [88, 56], [0, 50], [0, 50], [0, 50], [0, 50], [0, 50], [0, 50]]
sustainStep = 0

[params.line1.dcaEnv]
loop = false
stepCount = 2
steps = [[99, 99], [0, 30], [0, 50], [0, 50], [0, 50], [0, 50], [0, 50], [0, 50]]
sustainStep = 1

[params.line2]
algo = "cz101"
algoBlend = 0
algoControlsA = [{ id = "preset", value = 1 }, { id = "waveform1", value = 1 }, { id = "waveform2", value = 1 }, { id = "windowFunction", value = 0 }]
algoControlsB = []
baseWaveformA = "cosine"
baseWaveformB = "cosine"
dcaBase = 1
dcaKeyFollow = 6
dcwBase = 1
dcwKeyFollow = 6
detuneFine = 4
detuneNote = 0
modulation = 0
octave = 0
window = "off"

[params.line2.dcoEnv]
loop = false
stepCount = 1
steps = [[12, 99], [0, 50], [0, 50], [0, 50], [0, 50], [0, 50], [0, 50], [0, 50]]
sustainStep = 0

[params.line2.dcwEnv]
loop = false
stepCount = 3
steps = [[75, 94], [88, 35], [64, 45], [0, 50], [0, 50], [0, 50], [0, 50], [0, 50]]
sustainStep = 2

[params.line2.dcaEnv]
loop = false
stepCount = 2
steps = [[91, 95], [44, 55], [0, 50], [0, 50], [0, 50], [0, 50], [0, 50], [0, 50]]
sustainStep = 0

[params.portamento]
enabled = false
mode = "time"
rate = 0
time = 0.1

[params.lfo]
depth = 1
offset = 0
rate = 5
rateMode = "hz"
retrigger = false
symmetry = 0.5
syncDivision = "quarter"
waveform = "sine"

[params.lfo2]
depth = 0
offset = 0
rate = 5
rateMode = "hz"
retrigger = false
symmetry = 0.5
syncDivision = "quarter"
waveform = "sine"

[params.random]
rate = 2

[params.modEnv]
attack = 0.01
decay = 0.1
release = 0.2
sustain = 0.5

[params.fx.slot4]
type = "vibrato"

[params.fx.slot4.params]
delay = 6
depth = 16
enabled = true
rate = 54
rate_mode = "hz"
sync_division = "quarter"
waveform = 1
