format = "cosmo-preset"
formatVersion = 1
presetSchemaVersion = 1
id = "factory-075-ha-ha-ha"
name = "HA HA HA"
author = "Temple of CZ"
description = ""
tags = ["brass"]
starred = false
favorite = false
source = "cz-factory"

[params]
lineSelect = "L1"
modMode = "normal"
octave = 0
frequency = 440
volume = 1
polyMode = "poly8"
legato = false
velocityCurve = 0
pitchBendRange = 2
fxSlots = [{ type = "empty" }, { type = "empty" }, { type = "empty" }, { type = "vibrato", params = { enabled = true, waveform = 1, rate = 50, depth = 9, delay = 38 } }, { type = "empty" }, { type = "empty" }]

[params.line1]
algo = "cz101"
algo2 = "cz101"
algoBlend = 0
baseWaveformA = "cosine"
baseWaveformB = "cosine"
window = "off"
dcaBase = 1
dcwBase = 1
modulation = 0
detuneNote = 0
detuneFine = 0
octave = 0
dcwKeyFollow = 8
dcaKeyFollow = 8
algoControlsA = [{ id = "preset", value = 0 }, { id = "waveform1", value = 4 }, { id = "waveform2", value = 0 }, { id = "windowFunction", value = 0 }]
algoControlsB = [{ id = "preset", value = 0 }, { id = "waveform1", value = 0 }, { id = "waveform2", value = 0 }, { id = "windowFunction", value = 0 }]

[params.line1.dcoEnv]
steps = [[33, 64], [66, 46], [66, 50], [0, 50], [0, 50], [0, 50], [0, 50], [0, 50]]
sustainStep = 7
stepCount = 8
loop = false

[params.line1.dcwEnv]
steps = [[24, 99], [24, 14], [66, 22], [42, 33], [0, 22], [0, 50], [0, 50], [0, 50]]
sustainStep = 7
stepCount = 8
loop = false

[params.line1.dcaEnv]
steps = [[41, 74], [87, 62], [88, 34], [89, 17], [0, 66], [0, 50], [0, 50], [0, 50]]
sustainStep = 3
stepCount = 5
loop = false

[params.line2]
algo = "cz101"
algoBlend = 0
baseWaveformA = "cosine"
baseWaveformB = "cosine"
window = "off"
dcaBase = 1
dcwBase = 1
modulation = 0
detuneNote = 0
detuneFine = 0
octave = 0
dcwKeyFollow = 0
dcaKeyFollow = 0
algoControlsA = [{ id = "preset", value = 0 }, { id = "waveform1", value = 0 }, { id = "waveform2", value = 0 }, { id = "windowFunction", value = 0 }]
algoControlsB = []

[params.line2.dcoEnv]
steps = [[0, 50], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0]]
sustainStep = 1
stepCount = 2
loop = false

[params.line2.dcwEnv]
steps = [[99, 75], [99, 80], [99, 75], [0, 40], [0, 50], [0, 50], [0, 50], [0, 50]]
sustainStep = 2
stepCount = 4
loop = false

[params.line2.dcaEnv]
steps = [[99, 75], [79, 80], [79, 75], [0, 40], [0, 50], [0, 50], [0, 50], [0, 50]]
sustainStep = 2
stepCount = 4
loop = false

[params.portamento]
enabled = false
mode = "time"
rate = 0
time = 0.1

[params.lfo]
waveform = "sine"
rate = 5
depth = 1
symmetry = 0.5
retrigger = false
offset = 0

[params.lfo2]
waveform = "sine"
rate = 5
depth = 0
symmetry = 0.5
retrigger = false
offset = 0

[params.random]
rate = 2

[params.modEnv]
attack = 0.009999999776482582
decay = 0.10000000149011612
sustain = 0.5
release = 0.20000000298023224

[params.modMatrix]
routes = []
