format = "cosmo-preset"
formatVersion = 1
presetSchemaVersion = 1
id = "factory-206-heavenly-flute"
name = "Heavenly Flute"
author = "Purr Audio"
description = ""
tags = ["wind"]
starred = true
favorite = false
source = "cosmo-factory"
sortIndex = 3

[params]
lineSelect = "L2"
modMode = "normal"
octave = 0
frequency = 440
volume = 1
polyMode = "poly8"
legato = false
velocityCurve = 0
pitchBendRange = 2
fxSlots = [{ type = "vibrato", params = { enabled = true, waveform = 1, rate = 40, depth = 5.89589878490993, delay = 600 } }, { type = "phaser", params = { enabled = false, rate = 0.35, depth = 0.45, feedback = 0.2, mix = 0.25 } }, { type = "empty" }, { type = "empty" }, { type = "delay", params = { enabled = true, time = 0.5151404052734375, feedback = 0.46, mix = 0.344969482421875, tapeMode = true, warmth = 0.72 } }, { type = "shimmerVerb", params = { enabled = true, shimmer = 0.85, space = 0.95, mix = 0.11443969726562503 } }]

[params.line1]
algo = "cz101"
algoBlend = 0
baseWaveformA = "cosine"
baseWaveformB = "cosine"
window = "off"
dcaBase = 1
dcwBase = 1
modulation = 0
detuneNote = 0
detuneFine = 0
octave = 0
dcwKeyFollow = 0
dcaKeyFollow = 0
algoControlsA = [{ id = "preset", value = 4 }, { id = "waveform1", value = 5 }, { id = "waveform2", value = 5 }, { id = "windowFunction", value = 0 }]
algoControlsB = []

[params.line1.dcoEnv]
steps = [[0, 50], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0]]
sustainStep = 1
stepCount = 2
loop = false

[params.line1.dcwEnv]
steps = [[99, 75], [99, 80], [99, 75], [0, 40], [0, 50], [0, 50], [0, 50], [0, 50]]
sustainStep = 2
stepCount = 4
loop = false

[params.line1.dcaEnv]
steps = [[99, 75], [79, 80], [79, 75], [0, 40], [0, 50], [0, 50], [0, 50], [0, 50]]
sustainStep = 2
stepCount = 4
loop = false

[params.line2]
algo = "cz101"
algo2 = "cz101"
algoBlend = 0
baseWaveformA = "cosine"
baseWaveformB = "cosine"
window = "off"
dcaBase = 1
dcwBase = 1
modulation = 0
detuneNote = 0
detuneFine = 0
octave = 0
dcwKeyFollow = 2
dcaKeyFollow = 2
algoControlsA = [{ id = "preset", value = 2 }, { id = "waveform1", value = 2 }, { id = "waveform2", value = 2 }, { id = "windowFunction", value = 0 }]
algoControlsB = [{ id = "preset", value = 0 }, { id = "waveform1", value = 0 }, { id = "waveform2", value = 0 }, { id = "windowFunction", value = 0 }]

[params.line2.dcoEnv]
steps = [[0, 0], [0, 50], [0, 50], [0, 50], [0, 50], [0, 50], [0, 50], [0, 50]]
sustainStep = 0
stepCount = 1
loop = false

[params.line2.dcwEnv]
steps = [[49, 30], [0, 25], [70, 25], [0, 25], [60, 40], [0, 20], [80, 40], [0, 25]]
sustainStep = 0
stepCount = 8
loop = false

[params.line2.dcaEnv]
steps = [[99, 60], [46, 30], [0, 50], [0, 50], [0, 50], [0, 50], [0, 50], [0, 50]]
sustainStep = 0
stepCount = 2
loop = false

[params.portamento]
enabled = true
mode = "time"
rate = 85
time = 0.1

[params.lfo]
waveform = "sine"
rate = 2.000000000000001
depth = 1
symmetry = 0.5
retrigger = false
offset = 0

[params.lfo2]
waveform = "sine"
rate = 2.000000000000001
depth = 1
symmetry = 0.5
retrigger = false
offset = 0

[params.random]
rate = 2

[params.modEnv]
attack = 0.010000000000000007
decay = 0.10000000149011612
sustain = 0.5
release = 0.20000000298023224

[params.modMatrix]
routes = [{ source = "aftertouch", destination = "line2DcwEnvStep1Level", amount = 0.41596539837973445, enabled = true }]
