format = "cosmo-preset"
formatVersion = 1
presetSchemaVersion = 1
id = "factory-219-synth-bass"
name = "Synth Bass"
author = "Purr Audio"
description = ""
tags = ["bass"]
starred = false
favorite = false
source = "cosmo-factory"

[params]
lineSelect = "L1+L1'"
modMode = "ring"
octave = 0
frequency = 440
volume = 1
polyMode = "poly8"
legato = false
velocityCurve = 0
pitchBendRange = 2
fxSlots = [{ type = "vibrato", params = { enabled = true, waveform = 1, rate = 46, depth = 16, delay = 60 } }, { type = "phaseMod", params = { enabled = false, pmPre = false, amount = 0.01379699707031249, ratio = 2 } }, { type = "ringMod", params = { enabled = false, carrierHz = 1163.6280517578125, mix = 0.47427124023437495 } }, { type = "empty" }, { type = "wavefolder", params = { enabled = false, drive = 0.3, folds = 0.3, mix = 0.8 } }, { type = "compressor", params = { enabled = true, thresholdDb = -12, ratio = 4, attackMs = 5, releaseMs = 100, makeupDb = 6, mix = 1 } }]

[params.line1]
algo = "cz101"
algo2 = "cz101"
algoBlend = 0
baseWaveformA = "cosine"
baseWaveformB = "cosine"
window = "off"
dcaBase = 1
dcwBase = 1
modulation = 0
detuneNote = 0
detuneFine = 0
octave = -2
dcwKeyFollow = 7
dcaKeyFollow = 7
algoControlsA = [{ id = "preset", value = 0 }, { id = "waveform1", value = 5 }, { id = "waveform2", value = 2 }, { id = "windowFunction", value = 0 }]
algoControlsB = [{ id = "preset", value = 0 }, { id = "waveform1", value = 2 }, { id = "waveform2", value = 0 }, { id = "windowFunction", value = 0 }]

[params.line1.dcoEnv]
steps = [[0, 99], [0, 50], [0, 50], [0, 50], [0, 50], [0, 50], [0, 50], [0, 50]]
sustainStep = 0
stepCount = 1
loop = false

[params.line1.dcwEnv]
steps = [[99, 99], [79, 45], [15, 50], [0, 52], [0, 50], [0, 50], [0, 50], [0, 50]]
sustainStep = 2
stepCount = 4
loop = false

[params.line1.dcaEnv]
steps = [[99, 99], [0, 21], [0, 61], [0, 50], [0, 50], [0, 50], [0, 50], [0, 50]]
sustainStep = 1
stepCount = 3
loop = false

[params.line2]
algo = "cz101"
algo2 = "cz101"
algoBlend = 0
baseWaveformA = "cosine"
baseWaveformB = "cosine"
window = "off"
dcaBase = 1
dcwBase = 1
modulation = 0
detuneNote = 0
detuneFine = 0
octave = -1
dcwKeyFollow = 7
dcaKeyFollow = 7
algoControlsA = [{ id = "preset", value = 0 }, { id = "waveform1", value = 1 }, { id = "waveform2", value = 2 }, { id = "windowFunction", value = 0 }]
algoControlsB = [{ id = "preset", value = 0 }, { id = "waveform1", value = 2 }, { id = "waveform2", value = 0 }, { id = "windowFunction", value = 0 }]

[params.line2.dcoEnv]
steps = [[0, 99], [0, 50], [0, 50], [0, 50], [0, 50], [0, 50], [0, 50], [0, 50]]
sustainStep = 0
stepCount = 1
loop = false

[params.line2.dcwEnv]
steps = [[99, 97], [79, 43], [74, 50], [0, 52], [0, 50], [0, 50], [0, 50], [0, 50]]
sustainStep = 2
stepCount = 4
loop = false

[params.line2.dcaEnv]
steps = [[99, 99], [0, 21], [0, 61], [0, 50], [0, 50], [0, 50], [0, 50], [0, 50]]
sustainStep = 1
stepCount = 3
loop = false

[params.portamento]
enabled = false
mode = "time"
rate = 85
time = 0.1

[params.lfo]
waveform = "sine"
rate = 5
depth = 1
symmetry = 0.5
retrigger = false
offset = 0

[params.lfo2]
waveform = "sine"
rate = 5
depth = 0
symmetry = 0.5
retrigger = false
offset = 0

[params.random]
rate = 2

[params.modEnv]
attack = 0.009999999776482582
decay = 0.10000000149011612
sustain = 0.5
release = 0.20000000298023224

[params.modMatrix]
routes = []
