[vendor]
name = "Purr Audio"
id = "jp.cosmo"
url = "https://github.com/fpbrault/cosmo-pd"
au_manufacturer = "PurA"

[[plugin]]
crate = "cosmo-pd101-plugin"
name = "Cosmo PD-101"
category = "instrument"
fourcc = "Cpd3"
bundle_id = "ca.purraudio.cosmo-pd101"
