[vendor]
name = "Purr Audio"
id = "dev.purraudio"
url = "https://www.purraudio.dev/"
au_manufacturer = "PurA"

[[plugin]]
crate = "cosmo-pd101-plugin"
name = "Cosmo PD-101"
category = "instrument"
midi_input = true
midi_output = false
fourcc = "Copd"
au3_subtype = "Cpd3"
au_tag = "Synthesizer"
bundle_id = "dev.purraudio.cosmo-pd101"
windows_icon = "packages/cosmo-pd101-plugin/static/icons/cosmo-pd101.ico"
au_name = "Cosmo PD-101 (AUv2)"
au3_name = "Cosmo PD-101 (AUv3)"
macos_icon = "packages/cosmo-pd101-plugin/static/icons/cosmo-pd101.icns"

[packaging]
formats = ["clap", "vst3", "au2"]

[macos.packaging]
notarize = true

[windows.packaging]
publisher = "Purr Audio"
installer_icon = "packages/cosmo-pd101-plugin/static/icons/cosmo-pd101.ico"
