//! Generates Specta bindings for the plugin IPC bridge contract.
//!
//! Run with:
//!   cargo run -p cosmo-pd101-bridge-types --features specta-bindings --bin export-specta-bindings
//!
//! Optional env vars:
//! - SPECTA_TS_EXPORT_PATH: absolute/relative path to generated TypeScript file

use cosmo_pd101_bridge_types::{
    PluginIpcRequest, PresetSession, LoadPresetPayload,
};
use cosmo_synth_engine::params::SynthParams;
use specta::Types;
use specta_typescript::Typescript;

fn main() {
    let manifest_dir = env!("CARGO_MANIFEST_DIR");

    let ts_path = std::env::var("SPECTA_TS_EXPORT_PATH").unwrap_or_else(|_| {
        format!(
            "{manifest_dir}/../cosmo-pd101/src/lib/synth/bindings/plugin-bridge.ts"
        )
    });

    if let Some(ts_parent) = std::path::Path::new(&ts_path).parent() {
        std::fs::create_dir_all(ts_parent)
            .unwrap_or_else(|e| panic!("Failed to create TS output dir '{ts_parent:?}': {e}"));
    }

    let mut types = Types::default();
    types.register_mut::<PresetSession>();
    types.register_mut::<LoadPresetPayload>();
    types.register_mut::<PluginIpcRequest>();
    // Re-export engine types that appear in IPC responses
    types.register_mut::<SynthParams>();

    let config = Typescript::default();
    let mut out = String::new();
    out.push_str("// Generated by Specta. Do not edit manually.\n\n");
    out.push_str(
        &config
            .export(&types, specta_serde::Format)
            .expect("Failed to export types"),
    );

    // Generated IPC method map — maps each method name to its request/response types.
    // Response types are hand-curated here to match the Rust dispatch return types.
    // Keep this in sync with PluginIpcRequest variants.
    out.push_str("\n\n/** IPC method contract — maps method names to typed request/response pairs. */\n");
    out.push_str("export type PluginIpcMethods = {\n");
    out.push_str("  getParams: { request: null; response: SynthParams };\n");
    out.push_str("  setPresetSession: { request: PresetSession; response: null };\n");
    out.push_str("  loadPreset: { request: LoadPresetPayload; response: PresetSession };\n");
    out.push_str("};\n");

    std::fs::write(&ts_path, out)
        .unwrap_or_else(|e| panic!("Failed to write TypeScript bindings to '{ts_path}': {e}"));

    println!("[specta-bindings] Exported TypeScript plugin bridge bindings to: {ts_path}");
}
