//! Generates Specta bindings for the plugin IPC bridge contract.

use cosmo_pd101_bridge_types::{
    AddPresetPayload, AddPresetResponse, BridgeJsonValue, EditorState, ExportPresetResponse,
    FxModulePresetEntry, LoadPresetPayload, LoadPresetResponse, MidiLearnBinding, MidiLearnState,
    PluginIpcRequest, PluginIpcResponse, PresetBankBundle, PresetBankEntry, PresetBankMetadata,
    PresetLibraryActionResponse, PresetLibraryEntry, PresetLibraryResponse, PresetLibraryStatus,
    PresetLibrarySummaryEntry, PresetSession, RuntimeModSources, RuntimeVoiceDebugState,
    RuntimeVoiceEnvState, RuntimeVoiceLineState, SaveFxModulePresetPayload, SavePresetPayload,
    SavePresetResponse, ScopeDataResponse, TransportInfoResponse,
};
use cosmo_synth_engine::params::SynthParams;
use specta::Types;
use specta_typescript::Typescript;

fn main() {
    let manifest_dir = env!("CARGO_MANIFEST_DIR");
    let ts_path = std::env::var("SPECTA_TS_EXPORT_PATH").unwrap_or_else(|_| {
        format!("{manifest_dir}/../cosmo-pd101/src/lib/synth/bindings/plugin-bridge.ts")
    });

    if let Some(parent) = std::path::Path::new(&ts_path).parent() {
        std::fs::create_dir_all(parent)
            .unwrap_or_else(|error| panic!("failed to create '{parent:?}': {error}"));
    }

    let mut types = Types::default();
    types.register_mut::<BridgeJsonValue>();
    types.register_mut::<PresetSession>();
    types.register_mut::<EditorState>();
    types.register_mut::<MidiLearnBinding>();
    types.register_mut::<MidiLearnState>();
    types.register_mut::<ScopeDataResponse>();
    types.register_mut::<TransportInfoResponse>();
    types.register_mut::<RuntimeModSources>();
    types.register_mut::<RuntimeVoiceEnvState>();
    types.register_mut::<RuntimeVoiceLineState>();
    types.register_mut::<RuntimeVoiceDebugState>();
    types.register_mut::<PluginIpcRequest>();
    types.register_mut::<PluginIpcResponse>();
    types.register_mut::<LoadPresetPayload>();
    types.register_mut::<AddPresetPayload>();
    types.register_mut::<SavePresetPayload>();
    types.register_mut::<SaveFxModulePresetPayload>();
    types.register_mut::<PresetLibraryEntry>();
    types.register_mut::<PresetLibrarySummaryEntry>();
    types.register_mut::<PresetLibraryStatus>();
    types.register_mut::<PresetLibraryResponse>();
    types.register_mut::<PresetLibraryActionResponse>();
    types.register_mut::<LoadPresetResponse>();
    types.register_mut::<AddPresetResponse>();
    types.register_mut::<SavePresetResponse>();
    types.register_mut::<ExportPresetResponse>();
    types.register_mut::<FxModulePresetEntry>();
    types.register_mut::<PresetBankBundle>();
    types.register_mut::<PresetBankEntry>();
    types.register_mut::<PresetBankMetadata>();
    types.register_mut::<SynthParams>();

    let mut output = String::from("// Generated by Specta. Do not edit manually.\n\n");
    output.push_str(
        &Typescript::default()
            .export(&types, specta_serde::Format)
            .expect("failed to export bridge types"),
    );
    output.push_str(
        r#"

type PluginIpcMethod = PluginIpcRequest["method"];
type PluginIpcRequestFor<M extends PluginIpcMethod> =
  Extract<PluginIpcRequest, { method: M }>;
type PluginIpcResponseFor<M extends PluginIpcMethod> =
  Extract<PluginIpcResponse, { method: M }>;
type PluginIpcPayload<M extends PluginIpcMethod> =
  PluginIpcRequestFor<M> extends { payload: infer P } ? P : null;
type PluginIpcResult<M extends PluginIpcMethod> =
  PluginIpcResponseFor<M> extends { result: infer R } ? R : null;

type MissingPluginIpcResponses =
  Exclude<PluginIpcMethod, PluginIpcResponse["method"]>;
type ExtraPluginIpcResponses =
  Exclude<PluginIpcResponse["method"], PluginIpcMethod>;
type AssertNever<T extends never> = T;
type _AssertNoMissingPluginIpcResponses =
  AssertNever<MissingPluginIpcResponses>;
type _AssertNoExtraPluginIpcResponses =
  AssertNever<ExtraPluginIpcResponses>;

/** IPC contract generated entirely from Rust request and response enums. */
export type PluginIpcMethods = {
  [M in PluginIpcMethod]: {
    request: PluginIpcPayload<M>;
    response: PluginIpcResult<M>;
  };
};
"#,
    );

    std::fs::write(&ts_path, output)
        .unwrap_or_else(|error| panic!("failed to write '{ts_path}': {error}"));
    println!("[specta-bindings] Exported TypeScript plugin bridge bindings to: {ts_path}");
}
