//! Generates Specta bindings for the plugin IPC bridge contract.
//!
//! Run with:
//!   cargo run -p cosmo-pd101-bridge-types --features specta-bindings --bin export-specta-bindings
//!
//! Optional env vars:
//! - SPECTA_TS_EXPORT_PATH: absolute/relative path to generated TypeScript file

use cosmo_pd101_bridge_types::{
    AddPresetPayload, EditorState, LoadPresetPayload, MidiLearnBinding, MidiLearnState,
    PresetBankMetadata, PresetSession, ScopeDataResponse, TransportInfoResponse,
};
use cosmo_synth_engine::params::SynthParams;
use specta::Types;
use specta_typescript::Typescript;

fn main() {
    let manifest_dir = env!("CARGO_MANIFEST_DIR");

    let ts_path = std::env::var("SPECTA_TS_EXPORT_PATH").unwrap_or_else(|_| {
        format!("{manifest_dir}/../cosmo-pd101/src/lib/synth/bindings/plugin-bridge.ts")
    });

    if let Some(ts_parent) = std::path::Path::new(&ts_path).parent() {
        std::fs::create_dir_all(ts_parent)
            .unwrap_or_else(|e| panic!("Failed to create TS output dir '{ts_parent:?}': {e}"));
    }

    let mut types = Types::default();
    // Session & editor
    types.register_mut::<PresetSession>();
    types.register_mut::<EditorState>();
    // MIDI learn
    types.register_mut::<MidiLearnBinding>();
    types.register_mut::<MidiLearnState>();
    // Runtime
    types.register_mut::<ScopeDataResponse>();
    types.register_mut::<TransportInfoResponse>();
    // IPC payload structs (only those without serde_json::Value fields)
    types.register_mut::<LoadPresetPayload>();
    types.register_mut::<AddPresetPayload>();
    // Preset bank metadata (nested in PresetBankBundle — clean type)
    types.register_mut::<PresetBankMetadata>();
    // Engine re-exports
    types.register_mut::<SynthParams>();

    let config = Typescript::default();
    let mut out = String::new();
    out.push_str("// Generated by Specta. Do not edit manually.\n\n");
    out.push_str(
        &config
            .export(&types, specta_serde::Format)
            .expect("Failed to export types"),
    );

    // Generated IPC method map — maps each method name to typed request/response.
    // Response types are hand-curated to match Rust dispatch return types.
    out.push_str(
        "\n\n/** IPC method contract — maps method names to typed request/response pairs. */\n",
    );
    out.push_str("export type PluginIpcMethods = {\n");
    // Session
    out.push_str("  getPresetSession: { request: null; response: PresetSession };\n");
    out.push_str("  setPresetSession: { request: PresetSession; response: null };\n");
    out.push_str("  getPresetName: { request: null; response: string };\n");
    out.push_str("  setPresetName: { request: string; response: null };\n");
    out.push_str(
        "  loadPreset: { request: LoadPresetPayload; response: { preset_name: string } };\n",
    );
    out.push_str(
        "  loadPresetData: { request: { id: string }; response: { preset_name: string } };\n",
    );
    // Editor
    out.push_str("  getEditorState: { request: null; response: EditorState | null };\n");
    out.push_str("  setEditorState: { request: EditorState; response: null };\n");
    // MIDI learn
    out.push_str("  getMidiLearnState: { request: null; response: MidiLearnState };\n");
    out.push_str("  setMidiLearnMode: { request: boolean; response: null };\n");
    out.push_str("  setPendingMidiLearnParam: { request: string | null; response: null };\n");
    out.push_str("  addMidiBinding: { request: { paramKey: string; channel: number; cc: number }; response: null };\n");
    out.push_str("  removeMidiBinding: { request: MidiLearnBinding; response: null };\n");
    out.push_str("  clearMidiLearnBindings: { request: null; response: null };\n");
    // Synth
    out.push_str("  getParams: { request: null; response: SynthParams };\n");
    out.push_str("  setParams: { request: SynthParams; response: null };\n");
    out.push_str("  getParamsVersion: { request: null; response: number };\n");
    out.push_str("  getRuntimeModSources: { request: null; response: Record<string, number> };\n");
    out.push_str("  getRuntimeVoiceStates: { request: null; response: unknown };\n");
    out.push_str("  getTransportInfo: { request: null; response: TransportInfoResponse };\n");
    out.push_str("  getScopeData: { request: null; response: ScopeDataResponse };\n");
    out.push_str("  clientLog: { request: { level: string; message: string }; response: null };\n");
    // Performance
    out.push_str("  noteOn: { request: { note: number; velocity?: number }; response: null };\n");
    out.push_str("  noteOff: { request: { note: number }; response: null };\n");
    out.push_str("  sustain: { request: { on: boolean }; response: null };\n");
    out.push_str("  pitchBend: { request: { value: number }; response: null };\n");
    out.push_str("  modWheel: { request: { value: number }; response: null };\n");
    out.push_str("  aftertouch: { request: { value: number }; response: null };\n");
    out.push_str(
        "  polyAftertouch: { request: { note: number; value: number }; response: null };\n",
    );
    out.push_str("  macroValue: { request: { index: number; value: number }; response: null };\n");
    out.push_str("  panic: { request: null; response: null };\n");
    // Preset library — types containing serde_json::Value are hand-authored
    // because Specta forbids BigInt (i64/u64) inside serde_json::Value.
    out.push_str("  getPresetLibrary: { request: { source?: string } | null; response: { entries: PresetLibraryEntry[]; status: { state: string; message?: string } } };\n");
    out.push_str(
        "  retryPresetLibrary: { request: null; response: { status: { state: string } } };\n",
    );
    out.push_str("  repairPresetLibrary: { request: null; response: { status: { state: string }; backupPath?: string } };\n");
    out.push_str("  rebuildPresetLibrary: { request: null; response: { status: { state: string }; backupPath?: string } };\n");
    out.push_str("  addPreset: { request: AddPresetPayload; response: { id: string } };\n");
    out.push_str(
        "  savePreset: { request: SavePresetPayload; response: { id: string; name: string } };\n",
    );
    out.push_str("  deletePreset: { request: { id: string }; response: null };\n");
    out.push_str("  renamePreset: { request: { id: string; newName: string }; response: null };\n");
    out.push_str(
        "  toggleStarred: { request: { id: string; starred: boolean }; response: null };\n",
    );
    out.push_str(
        "  setPresetAuthor: { request: { id: string; author: string }; response: null };\n",
    );
    out.push_str("  setPresetDescription: { request: { id: string; description: string }; response: null };\n");
    out.push_str("  setPresetTags: { request: { id: string; tags: string[] }; response: null };\n");
    out.push_str("  importPresetBank: { request: PresetBankBundle; response: null };\n");
    out.push_str("  exportPreset: { request: { id: string }; response: { filename: string; json: string } };\n");
    out.push_str(
      "  listFxModulePresets: { request: { moduleType: string }; response: FxModulePresetEntry[] };\n",
  );
    out.push_str("  saveFxModulePreset: { request: SaveFxModulePresetPayload; response: FxModulePresetEntry };\n");
    out.push_str("  deleteFxModulePreset: { request: { id: string }; response: null };\n");
    out.push_str("};\n");

    // Hand-authored TS types that Specta cannot export (contain serde_json::Value).
    // These mirror the Rust structs in cosmo_pd101_bridge_types::preset and ::ipc.
    out.push_str("\n\n/** Preset library entry — mirrors Rust PresetLibraryEntry. */\n");
    out.push_str("export type PresetLibraryEntry = {\n");
    out.push_str("  id: string;\n");
    out.push_str("  name: string;\n");
    out.push_str("  source: string;\n");
    out.push_str("  author: string;\n");
    out.push_str("  description: string;\n");
    out.push_str("  starred: boolean;\n");
    out.push_str("  sortIndex: number;\n");
    out.push_str("  bankId: string | null;\n");
    out.push_str("  bankName: string | null;\n");
    out.push_str("  tags: string[];\n");
    out.push_str("  macroLabels: [string, string, string, string];\n");
    out.push_str("  factoryVersion: number;\n");
    out.push_str("  data: unknown;\n");
    out.push_str("};\n\n");

    out.push_str("/** FX module preset entry — mirrors Rust FxModulePresetEntry. */\n");
    out.push_str("export type FxModulePresetEntry = {\n");
    out.push_str("  id: string;\n");
    out.push_str("  name: string;\n");
    out.push_str("  moduleType: string;\n");
    out.push_str("  patch: Record<string, unknown>;\n");
    out.push_str("  updatedAtUnixMs: number;\n");
    out.push_str("};\n\n");

    out.push_str("/** Preset bank bundle — mirrors Rust PresetBankBundle. */\n");
    out.push_str("export type PresetBankBundle = {\n");
    out.push_str("  type: string;\n");
    out.push_str("  schemaVersion: number;\n");
    out.push_str("  bank: PresetBankMetadata;\n");
    out.push_str("  presets: PresetBankEntry[];\n");
    out.push_str("};\n\n");

    out.push_str("/** Preset bank entry — mirrors Rust PresetBankEntry. */\n");
    out.push_str("export type PresetBankEntry = {\n");
    out.push_str("  id: string;\n");
    out.push_str("  name: string;\n");
    out.push_str("  author: string;\n");
    out.push_str("  description: string;\n");
    out.push_str("  starred: boolean;\n");
    out.push_str("  tags: string[];\n");
    out.push_str("  data: unknown;\n");
    out.push_str("};\n\n");

    out.push_str("/** Save preset payload — mirrors Rust SavePresetPayload. */\n");
    out.push_str("export type SavePresetPayload = {\n");
    out.push_str("  id?: string;\n");
    out.push_str("  name: string;\n");
    out.push_str("  author: string;\n");
    out.push_str("  description: string;\n");
    out.push_str("  tags: string[];\n");
    out.push_str("  macroLabels?: string[];\n");
    out.push_str("  data?: unknown;\n");
    out.push_str("};\n\n");

    out.push_str(
        "/** Save FX module preset payload — mirrors Rust SaveFxModulePresetPayload. */\n",
    );
    out.push_str("export type SaveFxModulePresetPayload = {\n");
    out.push_str("  name: string;\n");
    out.push_str("  moduleType: string;\n");
    out.push_str("  patch: Record<string, unknown>;\n");
    out.push_str("};\n");

    std::fs::write(&ts_path, out)
        .unwrap_or_else(|e| panic!("Failed to write TypeScript bindings to '{ts_path}': {e}"));

    println!("[specta-bindings] Exported TypeScript plugin bridge bindings to: {ts_path}");
}
