//! Generates Specta bindings for synth wire/domain contracts.
//!
//! Run with:
//!   cargo run --features specta-bindings --bin export-specta-bindings
//!
//! Optional env vars:
//! - SPECTA_TS_EXPORT_PATH: absolute/relative path to generated TypeScript file

use cosmo_synth_engine::fx::{
    FxControlKindV1, FxControlOptionV1, FxControlV1, FxDefinitionV1, FxPresetOptionV1,
    fx_definitions_v1,
};
use cosmo_synth_engine::generators::{
    AlgoControlAssignmentV1, AlgoControlKindV1, AlgoControlOptionV1, AlgoControlPresentationV1,
    AlgoControlV1, AlgoDefinitionV1, AlgoUiEntryV1, CzPresetV1,
};
use cosmo_synth_engine::module_presets::{ModulePresetGroupV1, module_preset_catalog_v1};
use cosmo_synth_engine::params::engine_param_default_v1;
use cosmo_synth_engine::params::{
    Algo, AlgoControlValueV1, AutoWahParams, BaseWaveform, BitcrusherParams, ChorusParams,
    CompressorParams, CzAlgo, CzWaveform, DelayParams, DistortionParams, EnvStep, EqParams,
    FlangerParams, FxSlotConfig, FxSlotType, GrainDelayParams, JunoChorusParams, LfoParams,
    LfoRateMode, LfoSyncDivision, LfoWaveform, LineParams, LineSelect, LoFiParams,
    ModDestination, ModEnvParams, ModMatrix, ModMode, ModRoute, ModSource, MultimodeFilterParams,
    PhaseModParams, PhaserParams, PolyMode, PortamentoMode, PortamentoParams, RandomParams,
    ReverbParams, RingModParams, RotarySpeakerParams, ShimmerVerbParams, StepEnvData,
    StereoWidenerParams, SynthParams, TremoloParams, VibratoParams, WavefolderParams, WindowType,
    engine_param_ranges_v1, engine_param_ui_meta_v1,
};
use cosmo_synth_engine::preset_wire::{
    SynthPresetV1, algo_definitions_v1, algo_ui_catalog_v1, cz_presets,
};
use specta_typescript::{Typescript, export};

fn main() {
    let manifest_dir = env!("CARGO_MANIFEST_DIR");

    let ts_path = std::env::var("SPECTA_TS_EXPORT_PATH").unwrap_or_else(|_| {
        format!("{manifest_dir}/../cosmo-pd101/src/lib/synth/bindings/synth.ts")
    });

    if let Some(ts_parent) = std::path::Path::new(&ts_path).parent() {
        std::fs::create_dir_all(ts_parent)
            .unwrap_or_else(|e| panic!("Failed to create TS output dir '{ts_parent:?}': {e}"));
    }

    let config = Typescript::default();
    let mut out = String::new();
    out.push_str("// Generated by Specta. Do not edit manually.\n\n");
    // TODO: Replace this manual export list with automated graph export when
    // the workspace can move to a Specta toolchain version that supports it.
    out.push_str(&export::<EnvStep>(&config).expect("Failed to export EnvStep"));
    out.push_str("\n\n");
    out.push_str(&export::<StepEnvData>(&config).expect("Failed to export StepEnvData"));
    out.push_str("\n\n");
    out.push_str(&export::<CzAlgo>(&config).expect("Failed to export CzAlgo"));
    out.push_str("\n\n");
    out.push_str(&export::<CzWaveform>(&config).expect("Failed to export CzWaveform"));
    out.push_str("\n\n");
    out.push_str(&export::<BaseWaveform>(&config).expect("Failed to export BaseWaveform"));
    out.push_str("\n\n");
    out.push_str(&export::<Algo>(&config).expect("Failed to export Algo"));
    out.push_str("\n\n");
    out.push_str(&export::<WindowType>(&config).expect("Failed to export WindowType"));
    out.push_str("\n\n");
    out.push_str(&export::<LineSelect>(&config).expect("Failed to export LineSelect"));
    out.push_str("\n\n");
    out.push_str(&export::<ModMode>(&config).expect("Failed to export ModMode"));
    out.push_str("\n\n");
    out.push_str(&export::<PolyMode>(&config).expect("Failed to export PolyMode"));
    out.push_str("\n\n");
    out.push_str(&export::<LfoWaveform>(&config).expect("Failed to export LfoWaveform"));
    out.push_str("\n\n");
    out.push_str(&export::<LfoRateMode>(&config).expect("Failed to export LfoRateMode"));
    out.push_str("\n\n");
    out.push_str(&export::<LfoSyncDivision>(&config).expect("Failed to export LfoSyncDivision"));
    out.push_str("\n\n");
    out.push_str(&export::<PortamentoMode>(&config).expect("Failed to export PortamentoMode"));
    out.push_str("\n\n");
    out.push_str(&export::<ChorusParams>(&config).expect("Failed to export ChorusParams"));
    out.push_str("\n\n");
    out.push_str(&export::<DelayParams>(&config).expect("Failed to export DelayParams"));
    out.push_str("\n\n");
    out.push_str(&export::<ReverbParams>(&config).expect("Failed to export ReverbParams"));
    out.push_str("\n\n");
    out.push_str(&export::<PhaserParams>(&config).expect("Failed to export PhaserParams"));
    out.push_str("\n\n");
    out.push_str(&export::<VibratoParams>(&config).expect("Failed to export VibratoParams"));
    out.push_str("\n\n");
    out.push_str(&export::<PhaseModParams>(&config).expect("Failed to export PhaseModParams"));
    out.push_str("\n\n");
    out.push_str(&export::<RandomParams>(&config).expect("Failed to export RandomParams"));
    out.push_str("\n\n");
    out.push_str(&export::<ModEnvParams>(&config).expect("Failed to export ModEnvParams"));
    out.push_str("\n\n");
    out.push_str(&export::<PortamentoParams>(&config).expect("Failed to export PortamentoParams"));
    out.push_str("\n\n");
    out.push_str(&export::<LfoParams>(&config).expect("Failed to export LfoParams"));
    out.push_str("\n\n");
    out.push_str(
        &export::<AlgoControlValueV1>(&config).expect("Failed to export AlgoControlValueV1"),
    );
    out.push_str("\n\n");
    out.push_str(&export::<LineParams>(&config).expect("Failed to export LineParams"));
    out.push_str("\n\n");
    out.push_str(
        &export::<AlgoControlKindV1>(&config).expect("Failed to export AlgoControlKindV1"),
    );
    out.push_str("\n\n");
    out.push_str(
        &export::<AlgoControlPresentationV1>(&config)
            .expect("Failed to export AlgoControlPresentationV1"),
    );
    out.push_str("\n\n");
    out.push_str(
        &export::<AlgoControlAssignmentV1>(&config)
            .expect("Failed to export AlgoControlAssignmentV1"),
    );
    out.push_str("\n\n");
    out.push_str(
        &export::<AlgoControlOptionV1>(&config).expect("Failed to export AlgoControlOptionV1"),
    );
    out.push_str("\n\n");
    out.push_str(&export::<AlgoControlV1>(&config).expect("Failed to export AlgoControlV1"));
    out.push_str("\n\n");
    out.push_str(&export::<AlgoDefinitionV1>(&config).expect("Failed to export AlgoDefinitionV1"));
    out.push_str("\n\n");
    out.push_str(&export::<AlgoUiEntryV1>(&config).expect("Failed to export AlgoUiEntryV1"));
    out.push_str("\n\n");
    out.push_str(&export::<ModSource>(&config).expect("Failed to export ModSource"));
    out.push_str("\n\n");
    out.push_str(&export::<ModDestination>(&config).expect("Failed to export ModDestination"));
    out.push_str("\n\n");
    out.push_str(&export::<ModRoute>(&config).expect("Failed to export ModRoute"));
    out.push_str("\n\n");
    out.push_str(&export::<ModMatrix>(&config).expect("Failed to export ModMatrix"));
    out.push_str("\n\n");
    out.push_str(&export::<FxSlotType>(&config).expect("Failed to export FxSlotType"));
    out.push_str("\n\n");
    out.push_str(&export::<CompressorParams>(&config).expect("Failed to export CompressorParams"));
    out.push_str("\n\n");
    out.push_str(&export::<EqParams>(&config).expect("Failed to export EqParams"));
    out.push_str("\n\n");
    out.push_str(&export::<GrainDelayParams>(&config).expect("Failed to export GrainDelayParams"));
    out.push_str("\n\n");
    out.push_str(&export::<BitcrusherParams>(&config).expect("Failed to export BitcrusherParams"));
    out.push_str("\n\n");
    out.push_str(
        &export::<ShimmerVerbParams>(&config).expect("Failed to export ShimmerVerbParams"),
    );
    out.push_str("\n\n");
    out.push_str(&export::<DistortionParams>(&config).expect("Failed to export DistortionParams"));
    out.push_str("\n\n");
    out.push_str(&export::<JunoChorusParams>(&config).expect("Failed to export JunoChorusParams"));
    out.push_str("\n\n");
    out.push_str(&export::<RingModParams>(&config).expect("Failed to export RingModParams"));
    out.push_str("\n\n");
    out.push_str(&export::<TremoloParams>(&config).expect("Failed to export TremoloParams"));
    out.push_str("\n\n");
    out.push_str(&export::<WavefolderParams>(&config).expect("Failed to export WavefolderParams"));
    out.push_str("\n\n");
    out.push_str(&export::<LoFiParams>(&config).expect("Failed to export LoFiParams"));
    out.push_str("\n\n");
    out.push_str(
        &export::<MultimodeFilterParams>(&config).expect("Failed to export MultimodeFilterParams"),
    );
    out.push_str("\n\n");
    out.push_str(&export::<FlangerParams>(&config).expect("Failed to export FlangerParams"));
    out.push_str("\n\n");
    out.push_str(
        &export::<RotarySpeakerParams>(&config).expect("Failed to export RotarySpeakerParams"),
    );
    out.push_str("\n\n");
    out.push_str(&export::<AutoWahParams>(&config).expect("Failed to export AutoWahParams"));
    out.push_str("\n\n");
    out.push_str(
        &export::<StereoWidenerParams>(&config).expect("Failed to export StereoWidenerParams"),
    );
    out.push_str("\n\n");
    out.push_str(&export::<FxSlotConfig>(&config).expect("Failed to export FxSlotConfig"));
    out.push_str("\n\n");
    out.push_str(&export::<SynthParams>(&config).expect("Failed to export SynthParams"));
    out.push_str("\n\n");
    out.push_str(&export::<SynthPresetV1>(&config).expect("Failed to export SynthPresetV1"));
    out.push_str("\n\n");
    out.push_str(&export::<CzPresetV1>(&config).expect("Failed to export CzPresetV1"));
    out.push_str("\n\n");
    out.push_str(&export::<FxPresetOptionV1>(&config).expect("Failed to export FxPresetOptionV1"));
    out.push_str("\n\n");
    out.push_str(&export::<FxControlKindV1>(&config).expect("Failed to export FxControlKindV1"));
    out.push_str("\n\n");
    out.push_str(
        &export::<FxControlOptionV1>(&config).expect("Failed to export FxControlOptionV1"),
    );
    out.push_str("\n\n");
    out.push_str(&export::<FxControlV1>(&config).expect("Failed to export FxControlV1"));
    out.push_str("\n\n");
    out.push_str(&export::<FxDefinitionV1>(&config).expect("Failed to export FxDefinitionV1"));
    out.push_str("\n\n");
    out.push_str(
        &export::<ModulePresetGroupV1>(&config).expect("Failed to export ModulePresetGroupV1"),
    );
    out.push_str("\n\n");
    let catalog_json = serde_json::to_string_pretty(algo_ui_catalog_v1())
        .expect("Failed to serialize ALGO_UI_CATALOG_V1");
    let definitions_json = serde_json::to_string_pretty(algo_definitions_v1())
        .expect("Failed to serialize ALGO_DEFINITIONS_V1");
    out.push_str("\n\n");
    out.push_str("/** Rust-owned algorithm UI catalog. */\n");
    out.push_str("export const ALGO_UI_CATALOG_V1: AlgoUiEntryV1[] = ");
    out.push_str(&catalog_json);
    out.push_str(";\n");
    out.push_str("\n");
    out.push_str("/** Rust-owned algorithm definitions and control defaults. */\n");
    out.push_str("export const ALGO_DEFINITIONS_V1 = ");
    out.push_str(&definitions_json);
    out.push_str(";\n");
    out.push_str("\n");
    let cz_presets_json =
        serde_json::to_string_pretty(cz_presets()).expect("Failed to serialize CZ_PRESETS");
    out.push_str("/** Rust-owned CZ waveform combination presets. */\n");
    out.push_str("export const CZ_PRESETS: CzPresetV1[] = ");
    out.push_str(&cz_presets_json);
    out.push_str(";\n");
    out.push_str("\n");
    let fx_definitions_json = serde_json::to_string_pretty(fx_definitions_v1())
        .expect("Failed to serialize FX_DEFINITIONS_V1");
    out.push_str("/** Rust-owned FX module definitions and control defaults. */\n");
    out.push_str("export const FX_DEFINITIONS_V1: FxDefinitionV1[] = ");
    out.push_str(&fx_definitions_json);
    out.push_str(";\n");
    out.push_str("\n");
    let module_preset_catalog_json = serde_json::to_string_pretty(module_preset_catalog_v1())
        .expect("Failed to serialize MODULE_PRESET_CATALOG_V1");
    out.push_str("/** Rust-owned module preset labels and ordering. */\n");
    out.push_str("export const MODULE_PRESET_CATALOG_V1: ModulePresetGroupV1[] = ");
    out.push_str(&module_preset_catalog_json);
    out.push_str(";\n");
    out.push_str("\n");

    let mut engine_param_ui_meta_value = serde_json::to_value(engine_param_ui_meta_v1())
        .expect("Failed to serialize ENGINE_PARAM_UI_META_V1");
    if let Some(items) = engine_param_ui_meta_value.as_array_mut() {
        for item in items {
            if let Some(obj) = item.as_object_mut() {
                let key = obj.get("key").and_then(|v| v.as_str()).unwrap_or_default();
                match engine_param_default_v1(key) {
                    Some(default) => {
                        let rounded = (default * 1_000_000.0).round() / 1_000_000.0;
                        obj.insert(
                            "paramDefault".to_string(),
                            serde_json::Value::from(rounded as f64),
                        );
                    }
                    None => {
                        obj.insert("paramDefault".to_string(), serde_json::Value::Null);
                    }
                }
            }
        }
    }
    let engine_param_ui_meta_json = serde_json::to_string_pretty(&engine_param_ui_meta_value)
        .expect("Failed to serialize ENGINE_PARAM_UI_META_V1");
    let engine_param_ranges_json = serde_json::to_string_pretty(engine_param_ranges_v1())
        .expect("Failed to serialize ENGINE_PARAM_RANGES_V1");

    out.push_str("export type EngineEnumValueLabelV1 = { value: string; label: string };\n");
    out.push_str("export type EngineParamReadoutFormatV1 =\n");
    out.push_str("  | { kind: \"onOff\" }\n");
    out.push_str("  | { kind: \"raw\" }\n");
    out.push_str("  | { kind: \"uppercase\" }\n");
    out.push_str("  | { kind: \"integer\" }\n");
    out.push_str("  | { kind: \"decimal\" }\n");
    out.push_str("  | { kind: \"percent\" }\n");
    out.push_str("  | { kind: \"bipolarPercent\" }\n");
    out.push_str("  | { kind: \"degrees\" }\n");
    out.push_str("  | { kind: \"semitones\" }\n");
    out.push_str("  | { kind: \"milliseconds\" }\n");
    out.push_str("  | { kind: \"seconds2\" }\n");
    out.push_str("  | { kind: \"hertz\" }\n");
    out.push_str("  | { kind: \"enumMap\"; values: EngineEnumValueLabelV1[] };\n");
    out.push_str(
        "export type EngineParamUiMetaV1 = { key: string; readoutFormat: EngineParamReadoutFormatV1; paramDefault: number | null };\n"
    );
    out.push_str("export type EngineParamRangeV1 = { key: string; min: number; max: number };\n");
    out.push_str("/** Rust-owned engine parameter tooltip and readout metadata. */\n");
    out.push_str("export const ENGINE_PARAM_UI_META_V1: EngineParamUiMetaV1[] = ");
    out.push_str(&engine_param_ui_meta_json);
    out.push_str(";\n\n");
    out.push_str("/** Rust-owned numeric range metadata for engine parameters. */\n");
    out.push_str("export const ENGINE_PARAM_RANGES_V1: EngineParamRangeV1[] = ");
    out.push_str(&engine_param_ranges_json);
    out.push_str(";\n\n");
    std::fs::write(&ts_path, out)
        .unwrap_or_else(|e| panic!("Failed to write TypeScript bindings to '{ts_path}': {e}"));

    println!("[specta-bindings] Exported TypeScript bindings to: {ts_path}");
}
